### ISSUE TITLE
Immense build time

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#93]
Hi, first of all, thanks for the great tooling. We use it as a library in our tests. In our POC, we have observed an enormous build time in the Github Actions. Not sure, if it is related to Rust in general or if we can optimize it further.

**Comment by voxpelli** [comment]
Are you using `actions/cache` to cache anything in between your builds? https://github.com/actions/cache

See eg: https://stackoverflow.com/a/64702025/20667

That could probably help if you're not already doing it.

If you could share your full workflow file that could probably also help.

**Comment by StarpTech** [comment]
Hi, yes we are doing that. `make test` will build the compute service and run integration tests with viceroy.

```yaml
name: CI
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '*.md'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.54.0 # current Rust toolchain for Compute@Edge

    - name: Install Compute@Edge tooling
      uses: fastly/compute-actions/setup@main

    - uses: Swatinem/rust-cache@v1

    - name: Run tests
      working-directory: integration_tests
      run: make test
```

**Comment by cratelyn** [comment]
I'm not familiar with the `Swatinem/rust-cache@v1` action, but I see some Rust-specific examples in the `actions/cache` documentation that @/voxpelli mentioned above: https://github.com/actions/cache/blob/main/examples.md#rust---cargo

To save you a click, their example looks like this:

```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.cargo/bin/
      ~/.cargo/registry/index/
      ~/.cargo/registry/cache/
      ~/.cargo/git/db/
      target/
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```

Perhaps it would be worth giving this one a try, and seeing whether it improves your build times @StarpTech?

**Comment by StarpTech** [comment]
Hi @cratelyn, thanks. I'll give it a shoot.

**Comment by Integralist** [comment]
Also, interesting side note, if you add an `id: example_id` then other 'steps' in the Actions workflow can identify if there was a cache hit/miss and cause a separate step to be executed or skipped...

```yaml
- name: "do something if cache miss"
  if: steps.example_id.outputs.cache-hit != 'true'
  run: make do_the_thing
  shell: bash
```
