### ISSUE TITLE
Ignore markdown changes in CI

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#95]
it is possible to define our GitHub Actions so that we skip running our CI process when a PR contains only changes to `.md` files.

that looks something like this:

```yaml
name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '*.md'
```

this would make documentation updates easier to land in our project. :book: :love_letter:
